### ISSUE TITLE
OAuth authentication, e.g. for Google Mail

### ISSUE THREAD

**Issue by Paebbels** [txthinking/Mailer#11]
Is it possible that Mailer implements OAuth (oauth2) for SMTP, so users could send emails to e.g. Google while using an oauth token. An OAuth example for Google mail is available here: https://github.com/google/gmail-oauth2-tools/wiki/OAuth2DotPyRunThrough#testing-imap-and-smtp-authentication-with-oauth2

Kind regards
    Patrick Lehmann

**Comment by txthinking** [comment]
Is there any other mail provider who support OAuth with SMTP? Will this become the standard or trend?

**Comment by Paebbels** [comment]
Hello,
as far as I found out, OAuth is implemented in libsasl2, which is used for example in the mail transfer agents (MTAs) Cyrus and Postfix. These are two major mail servers used to build e-mail services in the scale of Google.

OAuth seems to be documented in https://tools.ietf.org/html/rfc7628

At a first view, it doesn't look very complicated.

**Comment by txthinking** [comment]
OK, I will read and do it in my spare time.

**Comment by Paebbels** [comment]
Thank you. I you decide to implement it, can you give me a short hint. There is another project (DokuWiki), which uses your Mailer, which I would like to support it ;). So if you implement it, the other project can update and the I can send mails to Google :).

**Comment by txthinking** [comment]
Now supported OAuth on develop branch.

Assuming you've got OAuth access token.
Instead of `->setAuth(USERNAME, PASSWORD)`, use `->setOAuth(OAUTH_ACCESS_TOKEN)`

You need to maintain the `access token` yourself.
If Gmail, see this sample: https://developers.google.com/gmail/api/quickstart/php#step_3_set_up_the_sample

**Comment by Paebbels** [comment]
Thanks, I'll forward your comment to the developer of my DokuWiki plugin.

**Comment by txthinking** [comment]
Released on `v1.4.0`.
If any issue, open a new task.
