### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by danio0701** [txthinking/Mailer#26]
Hi, I installed it by composer command but it don't work at all. 
I made index.php and input value which is in <code> section as example but always I get error: 

`Fatal error: Uncaught Error: Class "Tx\Mailer" not found in /smtp-mailer/vendor/index.php:8 Stack trace: #0 {main} thrown in /smtp-mailer/vendor/index.php on line 8`

no matter where I place index.php, I tested in every folder

Can anyone advice me something?

**Comment by daemionfox** [comment]
Sure, you have a code snippet we can look at?   

First thought is the "have you tried restarting your computer" type thought.   

Are you including **vendor/autoload.php** at thd top of your file?

**Comment by danio0701** [comment]
> Sure, you have a code snippet we can look at?
> 
> First thought is the "have you tried restarting your computer" type thought.
> 
> Are you including **vendor/autoload.php** at thd top of your file?

**Comment by danio0701** [comment]
> Sure, you have a code snippet we can look at?
> 
> First thought is the "have you tried restarting your computer" type thought.
> 
> Are you including **vendor/autoload.php** at thd top of your file?

Omg, I forgot about it. I add autoload.php

its my full code which I use:
`<?php
require __DIR__ . '/vendor/autoload.php';

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

use \Tx\Mailer;
use \Tx\Mailer\SMTP;
use \Tx\Mailer\Message;
use \Tx\Mailer\Exceptions\SMTPException;
use \Monolog\Logger;

$ok = (new Mailer())
    ->setServer('smtp-relay.gmail.com', 25)
    ->setAuth('djdiscobar.be@gmail.com', 'password')
    ->setFrom('dj', 'djdiscobar.be@gmail.com')
    ->setFakeFrom('Obama', 'fake@address.com') // if u want, a fake name, a fake email
    ->addTo('Jerry', 'knicat.bakery@yahoo.com')
    ->setSubject('Hello')
    ->setBody('Hi, Jerry! I <strong>love</strong> you.')
    //->addAttachment('host', '/etc/hosts')
    ->send();
var_dump($ok);`

Then I get error like this:
`Fatal error: Uncaught Tx\Mailer\Exceptions\CodeException: Unexpected return code - Expected: 334, Got: 503 | 503 5.5.1 bad sequence of commands w2sm259575ejc.3 - gsmtp in /smtp/vendor/txthinking/mailer/src/Mailer/SMTP.php:285 Stack trace: #0 /smtp/vendor/txthinking/mailer/src/Mailer/SMTP.php(178): Tx\Mailer\SMTP->authLogin() #1 /smtp/vendor/txthinking/mailer/src/Mailer.php(193): Tx\Mailer\SMTP->send() #2 /smtp/index.php(23): Tx\Mailer->send() #3 {main} thrown in /smtp/vendor/txthinking/mailer/src/Mailer/SMTP.php on line 285`
